#!/bin/bash

NC='\033[0m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
L_GREEN='\033[0;32m'

echo -e "
${BLUE}This is a simple password generator${NC}
"
i=1

read -p "How many password do you want to generate: " number

echo -e "
${RED}Please do not make any password under eight characters length !!${NC}
"
read -p "Enter length of the password to generate: " PASS_LENGTH
echo ' '


# Using Openssl
# rand ---> random characters
if [ "$PASS_LENGTH" -ge 8 ]; then
	for p in $(seq 1 $number); do
		password=$(openssl rand -base64 48 | cut -c1-$PASS_LENGTH)

		echo -e "Password $i: ${PURPLE}$password${NC}
	"

	i=$((i+1))

	done
else
	echo -e "
${RED}Not Recommended${NC} Sorry !!
Exiting..."

	exit 0
fi

read -p "Do you want to change any user account password [y/n]: " choice1

#echo "$choice1"

if [ "$choice1" = "n" ]; then

	echo -e "${L_GREEN}Ok gotcha!${NC}"
	echo "See ya...!! 
" | lolcat
	exit 0

elif [ "$choice1" = "y" ]; then

	#echo " in if"
	
	read -p "Which password do you want to use [Paste that password] ? " password

	user_grepped=$(sudo grep "[$]" /etc/shadow | cut -d ":" -f 1)

	#echo "$user_grepped"


	echo -e "${CYAN}$user_grepped${NC}" 
	echo "$user_grepped" > username.txt

	# Determining the this script's location
	Scrpt_PATH="`dirname \"$0\"`"
	
	mv username.txt $Scrpt_PATH

	read -p "
Which one ? " choice2

	match=$(grep -w $choice2 $Scrpt_PATH/username.txt)

	if [ "$match" = "$choice2" ]; then

		echo "matched"

        echo "$match:$password" | sudo chpasswd

        echo "Sucessfully Changed password !!" | lolcat
    fi

else
	echo "Cannot be understood"

fi
